#!/bin/ksh
export CFLAGS='-O2'
export CC=pgcc
export FC=pgf90
export F90=pgf90
export FFLAGS='-O2'
export F90FLAGS='-O2'
export M4=/usr/local/bin/m4
export ZLIB=~wrfhelp/external/zlib/zlib-1.2.3/pgi_i686
export JPEG=~wrfhelp/external/jpeg/jpeg-6b/pgi_i686
make clean
./configure --enable-fortran --with-zlib=$ZLIB --with-jpeg=$JPEG --prefix=$PWD
make all
make install
ranlib lib/*.a
