#!/bin/ksh
export CFLAGS='-O2'
export FC=pgcc
export F90=pgcc
export FFLAGS='-O2'
export F90FLAGS='-O2'
make clean
./configure --enable-fortran --prefix=$PWD
make all
make install

ranlib lib/*.a
rm src/*.o
