#!/bin/sh
# Meant to be run at the top level
./arch/configure_reader.py \
  arch/configure.defaults  \
  cmake/template/arch_config.cmake \
  wrf_config.cmake \
  CMakeLists.txt

# Now run cmake
mkdir -p _build/
cd _build
cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/../runTemp -DCMAKE_TOOLCHAIN_FILE=$PWD/../wrf_config.cmake
# cmake -S . -B _build 