      MODULE module_kma_wave2grid

      CONTAINS

#include "BSSLZ1.inc"
#include "CUT.inc"
#include "FFT991.inc"
#include "G2W.inc"
#include "G2WDZ.inc"
#include "G2WPP.inc"
#include "GAUSS.inc"
#include "GOUT.inc"
#include "IDCMP.inc"
#include "LGNDR1.inc"
#include "LGNUV.inc"
#include "LGNW2G.inc"
#include "LT2GAU.inc"
#include "MNMX.inc"
#include "RADB2M.inc"
#include "RADB3M.inc"
#include "RADB4M.inc"
#include "RADB5M.inc"
#include "RADBGM.inc"
#include "RADF2M.inc"
#include "RADF3M.inc"
#include "RADF4M.inc"
#include "RADF5M.inc"
#include "RADFGM.inc"
#include "REOWAV.inc"
#include "REOWV.inc"
#include "RESET.inc"
#include "RFFTBM.inc"
#include "RFFTFM.inc"
#include "RFFTIM.inc"
#include "RFTB1M.inc"
#include "RFTB2M.inc"
#include "RFTB9M.inc"
#include "RFTF1M.inc"
#include "RFTF2M.inc"
#include "RFTF3M.inc"
#include "RFTF9M.inc"
#include "RFTI1M.inc"
#include "SETARY.inc"
#include "W2G.inc"
#include "W2GCONV.inc"
#include "W2GPXY.inc"
#include "W2GUV.inc"
#include "WAVMAG.inc"
#include "WEIHT2.inc"
#include "ZNME2PXX.inc"
      END MODULE module_kma_wave2grid

