#!/bin/ksh
# cp INSTALL/make.inc.RS6K make.inc
# Edit make.inc
# Change FORTRAN and LOADER to 'xlf_r'
# Change OPTS to '-O2 -qmaxmem=32767 -qflttrap=zerodivide:invalid:nanq:enable -qsigtrap=xl__trce'
make clean
make lib
rm SRC/*.o
ranlib lapack_RS6K.a
ranlib tmglib_RS6K.a
ln -fs lapack_RS6K.a liblapack.a
ln -fs tmglib_RS6K.a libtmg.a
