#!/bin/ksh
cd src
export CPPFLAGS='-DNDEBUG -DIBMR2Fortran'
export CFLAGS='-O2'
export FC='xlf'
export F90='xlf'
export FFLAGS='-O2 -qnotextname'
export F90FLAGS='-O2 -qnoextname'
make clean
./configure
make all
make install
rm *.o
cd ..
ranlib lib/*.a
ln -fs lib/*.a .
