#!/bin/ksh

export NETCDF=~/external/netcdf/netcdf-3.6.1/ibm_powerpc
export CC=xlc
export NETCDF_INCDIR=$NETCDF/include
export NETCDF_LIBDIR=$NETCDF/lib
export NETCDF_LIBNAME='netcdf'
export X_LIBS='-L/usr/lpp/X11/lib/R6'
./configure
make
