#!/bin/ksh
export CFLAGS='-O2'
export FC='xlf'
export F90='xlf'
export FFLAGS='-O2'
export F90FLAGS='-O2'
make clean
./configure --enable-fortran --prefix=$PWD --without-pic
make all
make install

ln -s hdf5/lib .
ln -s hdf5/include .

ranlib lib/*.a
rm src/*.o
