#

mod_registry : ../../../Registry/Registry.EM_CHEM           
		touch run_wkc
		touch mod_registry
		touch ../mechanisms/*/*.kpp

# DEPENDENCIES : only dependencies after this line (don't remove the word DEPENDENCIES)

mod_registry:	../../Makefile_org ../inc 
