#!/bin/ksh
export CFLAGS='-O2 -lm'
export FC='g95'
export F90='g95'
export FFLAGS='-O2'
export F90FLAGS='-O2'
export ZLIB=~wrfhelp/external/zlib/zlib-1.2.3/pgi_powerpc
export JPEG=~wrfhelp/external/jpeg/jpeg-6b/pgi_powerpc
./configure --enable-fortran --with-zlib=$ZLIB --with-jpeg=$JPEG --prefix=$PWD
make all
make install
ranlib lib/*.a
