#!/bin/ksh
export CFLAGS='-O2'
export FC='pgf77'
export F90='pgf90'
export FFLAGS='-O2'
export F90FLAGS='-O2'
make clean
./configure --enable-fortran --prefix=$PWD --without-pic
make all
make install

ranlib lib/*.a
rm src/*.o
