#!/bin/ksh
cd src
# Edit Makefile to have
# FC=pgf90
# FC77=pgf77
# FFLAGS=-O2
# Edit Makefile_lib to comment out lapack.f
make clean
make lib_basic lib_cld lib_scat
rm *.o
ranlib *.a
cd ..
ln -fs src/librttov*.a librttov.a
