#!/bin/ksh
export CPPFLAGS="-C -P -traditional -DLINUX -Dlinux"
export CC=gcc
export FC=ifort
export FCFLAGS="-O2 -r8"
export CFLAGS="-O2 -DUNDERSCORE"
rm -f *.o *.a
$FC -c $FCFLAGS *.f
$FC -c $FCFLAGS *.F
$CC -c $CFLAGS *.c
ar -ruv libbufr.a *.o
rm *.o

