#

mod_registry.temp : ../../../Registry/Registry.EM_CHEM           
		touch run_wkc
		touch mod_registry.temp
		touch ../mechanisms/*/*.kpp

# DEPENDENCIES : only dependencies after this line (don't remove the word DEPENDENCIES)

mod_registry.temp:	../../Makefile_org ../inc 
