#!/bin/ksh
# cp INSTALL/make.inc.LINUX make.inc
# Edit make.inc
# Change FORTRAN and LOADER to 'g95'
# Change OPTS to '-O2 -r8'
make clean
make lib
rm SRC/*.o
ranlib lapack_LINUX.a
ranlib tmglib_LINUX.a
ln -fs lapack_LINUX.a liblapack.a
ln -fs tmglib_LINUX.a libtmg.a

