#!/bin/ksh
export AR="ar -ru"
export FC=g95
export CC=gcc
export FCFLAGS="-O3 -r8 -DF2CSTYLE"
export CCFLAGS="-O3 -DUNDERSCORE -DF2CSTYLE"
rm -f *.o *.a
$FC -c $FCFLAGS *.f
$CC -c $CCFLAGS *.c
$AR libbufr.a *.o
rm -rf *.o
