#!/bin/ksh
cd src
export CC='gcc'
export CXX='g++'
export CPPFLAGS='-DNDEBUG -Df2cFortran'
export CFLAGS='-O2'
export FC='g95'
export F90='g95'
export FFLAGS='-O2 -Df2cFortran'
export F90FLAGS='-O2 -Df2cFortran'

make clean
./configure
make all
make install
