#!/bin/ksh
export FC_EXTRA_FLAGS=-O2
# Edit make.macros and remove from LINUX_FLAGS_G95_PROD and _DEBUG the lines
# '-malign-double' and '-std=f95'
cd src
make clean
rm -f *.a
make g95
ranlib libCRTM.a
rm *.o
cd ..
ln -fs src/libCRTM.a libcrtm.a
