#!/bin/ksh
cd src
export CC='gcc'
export CXX='g++'
export CPPFLAGS='-DNDEBUG -DpgiFortran'
export CFLAGS='-O2'
export FC='g95'
export F90='g95'
export FFLAGS='-O2 -fno-second-underscore'
export F90FLAGS='-O2 -fno-second-underscore'

make clean
./configure
make
make install
cd ..
ln -fs lib/*.a .
