#!/bin/ksh
cd src
export CC='gcc'
export CXX='g++'
export CPPFLAGS='-DNDEBUG -DPATHSCALE_COMPILER'
export CFLAGS='-O2'
export FC='pathf90'
export F90='pathf90'
export FFLAGS='-O2'
export F90FLAGS='-O2'
make clean
./configure
make all
make install
rm *.o
cd ..
ln -s lib/*.a .
